### ISSUE TITLE
no rotor positions to output

### ISSUE THREAD

**Issue by antoniosap** [torognes/enigma#1]
i have decoded, but no rotor positions to output. how can i have ?

```
./enigma -c -u B -x 3
LBEIYRTPRXMHZWVSVBATCHBLDZFDVXTEUVRDKZFGRKTMPLINHQDUXTAVWYP
  162.4222 W: B123 R: AAA G: AAA S: BU CD EP FR IQ JY VW XZ
  171.8641 W: B123 R: AAA G: AAC S: BM CK DY EV HL NT
  179.4429 W: B123 R: AAA G: AAG S: BW CY DZ EF HK JX LV MP NO
  179.4435 W: B123 R: AAA G: AAI S: BW EY FH GX JT KP OU QS
  183.7916 W: B123 R: AAA G: AAL S: AE BR CY DO FK GX HN JQ PU SZ
  185.0199 W: B123 R: AAA G: ABQ S: AR BL CF DY EZ GN QW UV
  191.7843 W: B123 R: AAA G: ACA S: CE HP IK VW YZ
  194.8974 W: B123 R: AAA G: AIR S: DU EL FM GW IN JX KV QZ RY
  196.5305 W: B123 R: AAA G: AQT S: AK BN DU FS GZ JQ PX WY
  196.8895 W: B123 R: AAA G: ASS S: BU CK DR GW HM IL JY QX
  196.9637 W: B123 R: AAA G: AZM S: AF BW CH IQ MP OU SZ
  210.0439 W: B123 R: AAA G: BAH S: AJ BS CG FK OP QW RZ UV
  213.9919 W: B123 R: AAB G: EOX S: AY BV EL FK GU HW JP RS
  220.2416 W: B123 R: AAF G: EJF S: AW CF DV EY HX IU JK MQ NS OP
  229.1451 W: B123 R: AAX G: RRT S: AB CV GP HW IO LU MS QX TZ
  229.9481 W: B213 R: AAD G: JUS S: FJ
  235.8389 W: B213 R: AAE G: JUT S: FM
  251.8489 W: B213 R: AAF G: JUU S:
  258.2936 W: B213 R: AAG G: JUV S: FJ
  264.3030 W: B213 R: AAH G: JVW S:
  274.9000 W: B213 R: AAI G: JVX S:
  275.0850 W: B213 R: AAJ G: JVY S:
  283.3033 W: B213 R: AAK G: JVZ S:
  290.8969 W: B213 R: AAL G: JVA S:

BERLINERHABENESANDIESEMWOCHENENDESCHWERIHREZIELEZUERREICHEN

```

(and no option for output the partial decoded sting at each trial)

**Comment by torognes** [comment]
Hi, thanks for using the Enigma software.

The bottom line starting with "290.8969" (which is the score of the solution based on four-letter frequencies) indicates the settings for the best solution found.

The reflector (umkehrwalze) is B. The rotors used (walzenlage) are 2, 1, 3 (from left to right). The ring settings (ringstellung) are A, A, L (or 1, 1, 12). The rotor start settings (grundstellung) are J, V, A (or 9, 22, 1). There are no plugboard settings (steckerverbindungen) in the solution.

What are you missing?

The decrypted text is `BERLINERHABENESANDIESEMWOCHENENDESCHWERIHREZIELEZUERREICHEN`. With spaces inserted I guess it is should be `Berliner haben es an diesem wochenende schwer ihre ziele zu erreichen`, which I think in English means something like `Citizens of Berlin have a difficult time reaching their goals this weekend`.

**Comment by antoniosap** [comment]
the solution positions are B II I III RFL AAA S:NONE
and not AAL and JVA, the decoder missing print out the last rotor position

**Comment by torognes** [comment]
Both "RFL AAA" and "AAL JVA" are valid solutions and give the same results in this case. Many other combinations are also possible, e.g. ABL JWA, ..., BAL KVA, ..., RGL ABA, RHL ACA, ..., SFL BAA, TFL CAA, ..., ZZL IUA. The right most wheel settings must be L and A, while the settings of the two left most wheels can probably be set in almost 26*26 different positions as long as the difference between the rotor start position and the ring setting is kept constant. That is because the text is so short that no left wheel turnover will occur.
